// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: moto

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t *ui_Screen1;
lv_obj_t *ui_speedBar;
lv_obj_t *ui_compass;
lv_obj_t *ui_background;
lv_obj_t *ui_Image4;
lv_obj_t *ui_Image1;
lv_obj_t *ui_batteryLevel;
lv_obj_t *ui_Image3;
lv_obj_t *ui_lightIcon;
lv_obj_t *ui_speedUnit;
lv_obj_t *ui_speedValue;
lv_obj_t *ui_rangeLabel;
lv_obj_t *ui_Image8;
lv_obj_t *ui_tempLabel;
lv_obj_t *ui_currentMile;
lv_obj_t *ui_Image9;
lv_obj_t *ui_Image10;
lv_obj_t *ui_timeCost;
lv_obj_t *ui_batteryInd;
lv_obj_t *ui_kmLabel;
lv_obj_t *ui_Container1;
lv_obj_t *ui_Container2;
lv_obj_t *ui_leftArr;
lv_obj_t *ui_rightArr;
lv_obj_t *ui____initial_actions0;
const lv_img_dsc_t *ui_imgset_clk[1] = {&ui_img_clk2_png};
const lv_img_dsc_t *ui_imgset_guage_bg_[1] = {&ui_img_guage_bg_1_png};
const lv_img_dsc_t *ui_imgset_light[1] = {&ui_img_light23_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Screen1_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Screen1);
}
