// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: moto

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_speedBar = lv_bar_create(ui_Screen1);
lv_bar_set_value(ui_speedBar,65,LV_ANIM_OFF);
lv_bar_set_start_value(ui_speedBar, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_speedBar, 320);
lv_obj_set_height( ui_speedBar, 84);
lv_obj_set_x( ui_speedBar, 2 );
lv_obj_set_y( ui_speedBar, 12 );
lv_obj_set_align( ui_speedBar, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_speedBar, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_speedBar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_speedBar, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_speedBar, &ui_img_guage_bg_png, LV_PART_MAIN | LV_STATE_DEFAULT );

lv_obj_set_style_radius(ui_speedBar, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_speedBar, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_speedBar, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_speedBar, &ui_img_guage_indicator_png, LV_PART_INDICATOR | LV_STATE_DEFAULT );

ui_compass = lv_img_create(ui_Screen1);
lv_img_set_src(ui_compass, &ui_img_compas_png);
lv_obj_set_width( ui_compass, LV_SIZE_CONTENT);  /// 283
lv_obj_set_height( ui_compass, LV_SIZE_CONTENT);   /// 12
lv_obj_set_x( ui_compass, 186 );
lv_obj_set_y( ui_compass, -75 );
lv_obj_set_align( ui_compass, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_compass, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_compass, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_compass,512);

ui_background = lv_img_create(ui_Screen1);
lv_img_set_src(ui_background, &ui_img_devider_png);
lv_obj_set_width( ui_background, LV_SIZE_CONTENT);  /// 320
lv_obj_set_height( ui_background, LV_SIZE_CONTENT);   /// 240
lv_obj_set_x( ui_background, 1 );
lv_obj_set_y( ui_background, -3 );
lv_obj_set_align( ui_background, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_background, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_background, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image4 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image4, &ui_img_guage_bg_1_png);
lv_obj_set_width( ui_Image4, LV_SIZE_CONTENT);  /// 301
lv_obj_set_height( ui_Image4, LV_SIZE_CONTENT);   /// 107
lv_obj_set_x( ui_Image4, 5 );
lv_obj_set_y( ui_Image4, 1 );
lv_obj_set_align( ui_Image4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image4, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image1 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image1, &ui_img_battery_bg_png);
lv_obj_set_width( ui_Image1, LV_SIZE_CONTENT);  /// 24
lv_obj_set_height( ui_Image1, LV_SIZE_CONTENT);   /// 13
lv_obj_set_x( ui_Image1, 107 );
lv_obj_set_y( ui_Image1, -104 );
lv_obj_set_align( ui_Image1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_batteryLevel = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_batteryLevel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_batteryLevel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_batteryLevel, 137 );
lv_obj_set_y( ui_batteryLevel, -104 );
lv_obj_set_align( ui_batteryLevel, LV_ALIGN_CENTER );
lv_label_set_text(ui_batteryLevel,"100%");
lv_obj_set_style_text_color(ui_batteryLevel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_batteryLevel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_batteryLevel, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image3 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image3, &ui_img_temperature_png);
lv_obj_set_width( ui_Image3, LV_SIZE_CONTENT);  /// 32
lv_obj_set_height( ui_Image3, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_Image3, 99 );
lv_obj_set_y( ui_Image3, 100 );
lv_obj_set_align( ui_Image3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_lightIcon = lv_img_create(ui_Screen1);
lv_img_set_src(ui_lightIcon, &ui_img_light23_png);
lv_obj_set_width( ui_lightIcon, LV_SIZE_CONTENT);  /// 60
lv_obj_set_height( ui_lightIcon, LV_SIZE_CONTENT);   /// 41
lv_obj_set_x( ui_lightIcon, 56 );
lv_obj_set_y( ui_lightIcon, 100 );
lv_obj_set_align( ui_lightIcon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_lightIcon, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_lightIcon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_speedUnit = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_speedUnit, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_speedUnit, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_speedUnit, -114 );
lv_obj_set_y( ui_speedUnit, 17 );
lv_obj_set_align( ui_speedUnit, LV_ALIGN_CENTER );
lv_label_set_text(ui_speedUnit,"km/h");
lv_obj_set_style_text_color(ui_speedUnit, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_speedUnit, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_speedUnit, &ui_font_HollowPoint22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_speedValue = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_speedValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_speedValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_speedValue, -110 );
lv_obj_set_y( ui_speedValue, -27 );
lv_obj_set_align( ui_speedValue, LV_ALIGN_CENTER );
lv_label_set_text(ui_speedValue,"12");
lv_obj_set_style_text_color(ui_speedValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_speedValue, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_speedValue, &ui_font_HollowPoint, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_rangeLabel = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_rangeLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_rangeLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_rangeLabel, -127 );
lv_obj_set_y( ui_rangeLabel, 103 );
lv_obj_set_align( ui_rangeLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_rangeLabel,"range");
lv_obj_set_style_text_color(ui_rangeLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_rangeLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image8 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image8, &ui_img_range_bg_png);
lv_obj_set_width( ui_Image8, LV_SIZE_CONTENT);  /// 200
lv_obj_set_height( ui_Image8, LV_SIZE_CONTENT);   /// 5
lv_obj_set_x( ui_Image8, 60 );
lv_obj_set_y( ui_Image8, 74 );
lv_obj_set_align( ui_Image8, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image8, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_tempLabel = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_tempLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_tempLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_tempLabel, 128 );
lv_obj_set_y( ui_tempLabel, 102 );
lv_obj_set_align( ui_tempLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_tempLabel,"18C");
lv_obj_set_style_text_color(ui_tempLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_tempLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_tempLabel, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_currentMile = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_currentMile, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_currentMile, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_currentMile, 113 );
lv_obj_set_y( ui_currentMile, 53 );
lv_obj_set_align( ui_currentMile, LV_ALIGN_CENTER );
lv_label_set_text(ui_currentMile,"123 km");
lv_obj_set_style_text_color(ui_currentMile, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_currentMile, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_currentMile, &ui_font_HollowPoint32, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image9 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image9, &ui_img_range_knob_png);
lv_obj_set_width( ui_Image9, LV_SIZE_CONTENT);  /// 40
lv_obj_set_height( ui_Image9, LV_SIZE_CONTENT);   /// 20
lv_obj_set_x( ui_Image9, 39 );
lv_obj_set_y( ui_Image9, 55 );
lv_obj_set_align( ui_Image9, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image9, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image9, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image10 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image10, &ui_img_clk2_png);
lv_obj_set_width( ui_Image10, LV_SIZE_CONTENT);  /// 40
lv_obj_set_height( ui_Image10, LV_SIZE_CONTENT);   /// 40
lv_obj_set_x( ui_Image10, -50 );
lv_obj_set_y( ui_Image10, 101 );
lv_obj_set_align( ui_Image10, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image10, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image10, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_timeCost = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_timeCost, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_timeCost, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_timeCost, -12 );
lv_obj_set_y( ui_timeCost, 101 );
lv_obj_set_align( ui_timeCost, LV_ALIGN_CENTER );
lv_label_set_text(ui_timeCost,"12:23");
lv_obj_set_style_text_color(ui_timeCost, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_timeCost, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_timeCost, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_batteryInd = lv_bar_create(ui_Screen1);
lv_bar_set_value(ui_batteryInd,25,LV_ANIM_OFF);
lv_bar_set_start_value(ui_batteryInd, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_batteryInd, 17);
lv_obj_set_height( ui_batteryInd, 7);
lv_obj_set_x( ui_batteryInd, 106 );
lv_obj_set_y( ui_batteryInd, -104 );
lv_obj_set_align( ui_batteryInd, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_batteryInd, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_batteryInd, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_batteryInd, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_batteryInd, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_batteryInd, lv_color_hex(0x08F655), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_batteryInd, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_kmLabel = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_kmLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_kmLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_kmLabel, 115 );
lv_obj_set_y( ui_kmLabel, 26 );
lv_obj_set_align( ui_kmLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_kmLabel,"123 km");
lv_obj_set_style_text_color(ui_kmLabel, lv_color_hex(0x00FFA5), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_kmLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_kmLabel, &ui_font_HollowPoint32, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container1 = lv_obj_create(ui_Screen1);
lv_obj_remove_style_all(ui_Container1);
lv_obj_set_width( ui_Container1, 159);
lv_obj_set_height( ui_Container1, 19);
lv_obj_set_x( ui_Container1, -102 );
lv_obj_set_y( ui_Container1, -76 );
lv_obj_set_align( ui_Container1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Container1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Container1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container2 = lv_obj_create(ui_Screen1);
lv_obj_remove_style_all(ui_Container2);
lv_obj_set_width( ui_Container2, 149);
lv_obj_set_height( ui_Container2, 17);
lv_obj_set_x( ui_Container2, 103 );
lv_obj_set_y( ui_Container2, -75 );
lv_obj_set_align( ui_Container2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Container2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Container2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_leftArr = lv_img_create(ui_Screen1);
lv_img_set_src(ui_leftArr, &ui_img_left_arr_png);
lv_obj_set_width( ui_leftArr, LV_SIZE_CONTENT);  /// 50
lv_obj_set_height( ui_leftArr, LV_SIZE_CONTENT);   /// 35
lv_obj_set_x( ui_leftArr, -122 );
lv_obj_set_y( ui_leftArr, -73 );
lv_obj_set_align( ui_leftArr, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_leftArr, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_leftArr, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_rightArr = lv_img_create(ui_Screen1);
lv_img_set_src(ui_rightArr, &ui_img_left_arr_png);
lv_obj_set_width( ui_rightArr, LV_SIZE_CONTENT);  /// 50
lv_obj_set_height( ui_rightArr, LV_SIZE_CONTENT);   /// 35
lv_obj_set_x( ui_rightArr, 113 );
lv_obj_set_y( ui_rightArr, -73 );
lv_obj_set_align( ui_rightArr, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_rightArr, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_rightArr, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_angle(ui_rightArr,1800);

ui_gpsIcon = lv_img_create(ui_Screen1);
lv_img_set_src(ui_gpsIcon, &ui_img_gps_png);
lv_obj_set_width( ui_gpsIcon, LV_SIZE_CONTENT);  /// 32
lv_obj_set_height( ui_gpsIcon, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_gpsIcon, -140 );
lv_obj_set_y( ui_gpsIcon, -108 );
lv_obj_set_align( ui_gpsIcon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_gpsIcon, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_gpsIcon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_gpsNum = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_gpsNum, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_gpsNum, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_gpsNum, -105 );
lv_obj_set_y( ui_gpsNum, -107 );
lv_obj_set_align( ui_gpsNum, LV_ALIGN_CENTER );
lv_label_set_text(ui_gpsNum,"0");
lv_obj_set_style_text_color(ui_gpsNum, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_gpsNum, 255, LV_PART_MAIN| LV_STATE_DEFAULT);


}
